691205638491078656:
    auto_send_channel: 904739893987643393
    school_name: 역곡고등학교
    server_name: 거상이네
720657471361777724:
    auto_send_channel: 0
    school_name: 송라중학교
    server_name: 너무달아 ㅋ
734359823071707158:
    auto_send_channel: 803184556471615488
    school_name: 가림고등학교
    server_name: seeex
756307340390694934:
    auto_send_channel: 0
    school_name: 여월중학교
    server_name: 광식랜드
764804837497896962:
    auto_send_channel: 0
    school_name: ''
    server_name: 종합 붕붕이노
794226624232161311:
    auto_send_channel: 894311607826522193
    school_name: 가림고등학교
    server_name: madmens house
816408797593075712:
    auto_send_channel: 0
    school_name: ''
    server_name: Lanturn
823525631735496755:
    auto_send_channel: 0
    school_name: 신평중학교
    server_name: 땃쥐
825583145554280488:
    auto_send_channel: 0
    school_name: 충의중학교
    server_name: 충의중 2 - 3
827841865155608576:
    auto_send_channel: 0
    school_name: ''
    server_name: 진이YouTube
839834080744701982:
    auto_send_channel: 841879265939292173
    school_name: 가림고등학교
    server_name: 가림고 2학년 4반
843047337123119116:
    auto_send_channel: 0
    school_name: 순천왕의중학교
    server_name: 1-4
864738231055679519:
    auto_send_channel: 0
    school_name: ''
    server_name: 고블린 오두막
881405287653851176:
    auto_send_channel: 0
    school_name: 대방중학교
    server_name: 서버
887634804835749898:
    auto_send_channel: 0
    school_name: 목포덕인중학교
    server_name: None
888044405020311612:
    auto_send_channel: 0
    school_name: 전주새연초증학교
    server_name: 우리들의 게임 이야기
893435805706620928:
    auto_send_channel: 0
    school_name: 화명중학교
    server_name: 옵치 수다방
895929232914518056:
    auto_send_channel: 0
    school_name: 목포덕인중학교
    server_name: None
899650427027603518:
    auto_send_channel: 0
    school_name: 의림여자중학교
    server_name: 우리 가좆들
902007695643668540:
    auto_send_channel: 911890953336397845
    school_name: 충일중학교
    server_name: 꿀벌들의 나라
903157257418719262:
    auto_send_channel: 0
    school_name: ''
    server_name: 괴물쥐를 위한 서버
903662079913918524:
    auto_send_channel: 0
    school_name: ''
    server_name: 관관이네
903927650563801088:
    auto_send_channel: 0
    school_name: ''
    server_name: 대전 오류초등학교
906533130754736178:
    auto_send_channel: 0
    school_name: ''
    server_name: 신평중 겜방
